In [1]:
# Part 1: Load a Dataset & Check Missing Values

# Task 1: Titanic Dataset
# - Load the dataset using Pandas.
# - Check for missing values in the 'Age' column.






# Part 1: Load a Dataset & Check Missing Values

import pandas as pd

# Load the Titanic dataset from a URL (public CSV)
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df = pd.read_csv(url)

# Show first few rows
print("🔹 First 5 rows of the dataset:")
print(df.head())

# Check for missing values in the 'Age' column
print("\n🔍 Missing values in 'Age' column:")
print(df['Age'].isnull().sum())



# Part 2: Identify Duplicates & Inconsistencies

# Find duplicate rows
duplicates = df[df.duplicated()]

print("\n🧯 Number of duplicate rows:", len(duplicates))
if not duplicates.empty:
    print("Sample duplicate rows:")
    print(duplicates.head())
else:
    print("No duplicate rows found.")



# Part 3: Generate a Data Quality Report

print("\n📋 Data Quality Report:")

# 1. Missing values per column
missing_report = df.isnull().sum()
print("\nMissing values per column:")
print(missing_report[missing_report > 0])

# 2. Total duplicate rows
print("\nTotal duplicate rows:", df.duplicated().sum())

# 3. Basic statistics
print("\nDescriptive statistics:")
print(df.describe(include='all'))

# Part 2: Identify Duplicates & Inconsistencies

# Task 2: Duplicate Rows in Titanic Dataset
# - Identify any duplicate rows in the dataset.










# Part 3: Generate a Data Quality Report

# Task 3: Titanic Dataset Overview
# - Create a simple report of missing values, duplicates, and some basic statistics for the Titanic dataset.

🔹 First 5 rows of the dataset:
   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0

   Parch            Ticket     Fare Cabin Embarked
0      0         A/5 21171   7.2500   NaN        S
1      0          PC 17599  71.2833   C85        C
2      0  STON/O2. 3101282   7.9250   NaN        S
3      0            113803  53.1000  C123        S
4      0            373450   8.0500   NaN        S

🔍 Missing values in 'Age' column:
177

🧯 Number of duplicate rows: 0
No duplicate rows found.

📋 Data Quality Report:

Missing values per column:
Age         177
Cabin       687
Embarked      2
dtype: int64

Total duplicate rows: 0

Descriptive statistics:
        PassengerId    Survived      Pclass                 Name   Sex  \
count    891.000000  891.000000  891.000000                  891   891
unique          NaN         NaN         NaN                  891     2
top             NaN         NaN         NaN  Dooley, Mr. Patrick  male
freq            NaN         NaN         NaN                    1   577
mean     446.000000    0.383838    2.308642                  NaN   NaN
std      257.353842    0.486592    0.836071                  NaN   NaN
min        1.000000    0.000000    1.000000                  NaN   NaN
25%      223.500000    0.000000    2.000000                  NaN   NaN
50%      446.000000    0.000000    3.000000                  NaN   NaN
75%      668.500000    1.000000    3.000000                  NaN   NaN
max      891.000000    1.000000    3.000000                  NaN   NaN

               Age       SibSp       Parch  Ticket        Fare Cabin Embarked
count   714.000000  891.000000  891.000000     891  891.000000   204      889
unique         NaN         NaN         NaN     681         NaN   147        3
top            NaN         NaN         NaN  347082         NaN    G6        S
freq           NaN         NaN         NaN       7         NaN     4      644
mean     29.699118    0.523008    0.381594     NaN   32.204208   NaN      NaN
std      14.526497    1.102743    0.806057     NaN   49.693429   NaN      NaN
min       0.420000    0.000000    0.000000     NaN    0.000000   NaN      NaN
25%      20.125000    0.000000    0.000000     NaN    7.910400   NaN      NaN
50%      28.000000    0.000000    0.000000     NaN   14.454200   NaN      NaN
75%      38.000000    1.000000    0.000000     NaN   31.000000   NaN      NaN
max      80.000000    8.000000    6.000000     NaN  512.329200   NaN      NaN